USE OPTUS;

INSERT INTO EMPRESA(nomeEmpresa)
VALUES('SPOTIFY'), ('DEEZER')

INSERT INTO ALBUM(idEmpresa,nomeAlbum)
VALUES(2, 'BLURRYFACE'), (1, 'NOTHING HAPPENS')

INSERT INTO ESTILO(idAlbum,estilo1,estilo2)
VALUES(2, 'ALTERNATIVE', 'INDIE'), (1, 'INDIE', 'POP')

INSERT INTO USUARIO(idEmpresa,nome,email,senha,tipoPermissao)
VALUES (1, 'YURI', 'YURI@GMAIL.COM', 'YURI123', 1), (2, 'HENRIQUE', 'HENRIQUE@GMAIL.COM', 'HENRIQUE123', 0)