CREATE DATABASE OPTUS;
GO

USE OPTUS;
GO

CREATE TABLE EMPRESA(
	idEmpresa INT PRIMARY KEY IDENTITY(1,1),
	nomeEmpresa VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE ALBUM(
	idAlbum INT PRIMARY KEY IDENTITY(1,1),
	idEmpresa INT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
	nomeAlbum VARCHAR(30),
	anoLancamento SMALLINT,
	nomeArtista VARCHAR(30)
);

CREATE TABLE ESTILO(
	idEstilo INT PRIMARY KEY IDENTITY(1,1),
	nomeEstilo VARCHAR(30),
);

CREATE TABLE ALBUM_ESTILO(
	idAlbum INT FOREIGN KEY REFERENCES ALBUM(idAlbum),
	idEstilo INT FOREIGN KEY REFERENCES ESTILO(idEstilo)
);

CREATE TABLE USUARIO(
	idUsuario INT PRIMARY KEY IDENTITY(1,1),
	idEmpresa INT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
	nome VARCHAR(30),
	email VARCHAR(30),
	senha VARCHAR(30),
	tipoPermissao BIT
);
