CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

CREATE TABLE VEICULO(
	idVeiculo INT PRIMARY KEY IDENTITY(1,1),
	placaVeiculo VARCHAR(7) NOT NULL UNIQUE
);
GO

CREATE TABLE EMPRESA(
	idEmpresa INT PRIMARY KEY IDENTITY(1,1),
	idVeiculo INT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	nomeEmpresa VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE MARCA(
	idMarca INT PRIMARY KEY IDENTITY(1,1),
	nomeMarca VARCHAR(20)
);

CREATE TABLE MODELO(
	idModelo INT PRIMARY KEY IDENTITY(1,1),
	idVeiculo INT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	idMarca INT FOREIGN KEY REFERENCES MARCA(idMarca),
	nomeModelo VARCHAR(30)
);

CREATE TABLE CLIENTE(
	idCliente INT PRIMARY KEY IDENTITY(1,1),
	idVeiculo INT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	nomeCliente VARCHAR(40),
	cpfCliente VARCHAR(11)
);
