CREATE DATABASE PCLINICS;
GO

USE PCLINICS;
GO

CREATE TABLE CLINICA(
	idClinica INT PRIMARY KEY IDENTITY(1,1),
	nomeClinica VARCHAR(30) NOT NULL UNIQUE,
	enderecoClinica VARCHAR(70) NOT NULL UNIQUE
);

CREATE TABLE VETERINARIO(
	idVeterinario INT PRIMARY KEY IDENTITY(1,1),
	idClinica INT FOREIGN KEY REFERENCES CLINICA(idClinica),
	nomeVeterinario VARCHAR(50) NOT NULL 
);

CREATE TABLE DONO(
	idDono INT PRIMARY KEY IDENTITY(1,1),
	nomeDono VARCHAR(50) NOT NULL 
);

CREATE TABLE TIPOPET(
	idTipoPet INT PRIMARY KEY IDENTITY(1,1),
	tipoPet VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE RACA(
	idRaca INT PRIMARY KEY IDENTITY(1,1),
	idTipoPet INT FOREIGN KEY REFERENCES TIPOPET(idTipoPet),
	racaPet VARCHAR(30)  NOT NULL UNIQUE
);

CREATE TABLE PET(
	idPet INT PRIMARY KEY IDENTITY(1,1),
	idDono INT FOREIGN KEY REFERENCES DONO(idDono),
	idRaca INT FOREIGN KEY REFERENCES RACA(idRaca),
	nomePet VARCHAR(30) NOT NULL,
	dataNascimentoPet DATE
);

CREATE TABLE ATENDIMENTO(
	idAtendimento INT PRIMARY KEY IDENTITY(1,1),
	idPet INT FOREIGN KEY REFERENCES PET(idPet),
	idVeterinario INT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
	dataAtendimento DATE
);