USE PCLINICS;

SELECT * FROM CLINICA
SELECT * FROM VETERINARIO
SELECT * FROM DONO
SELECT * FROM TIPOPET
SELECT * FROM RACA
SELECT * FROM PET
SELECT * FROM ATENDIMENTO

SELECT nomeVeterinario, crmv, nomeClinica
FROM VETERINARIO
LEFT JOIN CLINICA
ON CLINICA.idClinica = VETERINARIO.idVeterinario
WHERE CLINICA.idClinica = 1

SELECT racaPET
FROM RACA
LEFT JOIN CLINICA
ON CLINICA.idClinica = RACA.idRaca
WHERE racaPet LIKE 'S%'

SELECT tipoPet
FROM CLINICA
LEFT JOIN TIPOPET
ON CLINICA.idClinica = TIPOPET.idTipoPet
WHERE tipoPet LIKE '%O'

SELECT nomePet, nomeDono
FROM CLINICA
LEFT JOIN PET
ON CLINICA.idClinica = PET.idPet
LEFT JOIN DONO
ON CLINICA.idClinica = DONO.idDono

SELECT idAtendimento, nomeVeterinario, nomePet, racaPet, tipoPet, nomeDono, nomeClinica
FROM CLINICA
LEFT JOIN ATENDIMENTO
ON CLINICA.idClinica = ATENDIMENTO.idAtendimento
LEFT JOIN VETERINARIO
ON CLINICA.idClinica = VETERINARIO.idVeterinario
LEFT JOIN PET
ON CLINICA.idClinica = PET.idPet
LEFT JOIN DONO
ON CLINICA.idClinica = DONO.idDono
LEFT JOIN TIPOPET
ON CLINICA.idClinica = TIPOPET.idTipoPet
LEFT JOIN RACA
ON CLINICA.idClinica = RACA.idRaca
